name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or your desired Python version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            zip \
            libncurses5-dev \
            pkg-config \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            openjdk-17-jdk 

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer
          
      - name: Install Cython
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython

      - name: Install Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-30" "ndk;21.4.7075529"
          echo "android.sdk = $ANDROID_HOME" >> buildozer.spec
          echo "android.ndk = $ANDROID_HOME/ndk/21.4.7075529" >> buildozer.spec
          echo "android.jdk = /usr/lib/jvm/java-17-openjdk-amd64" >> buildozer.spec

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer build directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build Android APK (Debug)
        run: buildozer android debug

      - name: Upload Debug APK
        uses: actions/upload-pages-artifact@v3
        with:
          name: debug-apk
          path: bin/*.apk
