name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v2
        id: buildozer
        with:
          workdir: .
          buildozer_version: git+https://github.com/kuzeyron/buildozer.git@cutouts
          command: sudo /usr/bin/python3 -m pip install cython==0.29.33 && pip3 install cython==0.29.33 && buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: package-kivyhome
          path: ${{ steps.buildozer.outputs.filename }}
